In [5]:
import visdom
import numpy as np

In [21]:
viz = visdom.Visdom(server='http://localhost', port='8097')

In [22]:
Y  = np.linspace(-5, 5, 11)
Y.shape

(11,)

In [23]:
(Y, Y)


(array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.]),
 array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.]))

In [24]:
np.column_stack((Y, Y))

array([[-5., -5.],
       [-4., -4.],
       [-3., -3.],
       [-2., -2.],
       [-1., -1.],
       [ 0.,  0.],
       [ 1.,  1.],
       [ 2.,  2.],
       [ 3.,  3.],
       [ 4.,  4.],
       [ 5.,  5.]])

In [29]:
np.column_stack((Y * Y, np.sqrt(Y + 5)))

array([[25.        ,  0.        ],
       [16.        ,  1.        ],
       [ 9.        ,  1.41421356],
       [ 4.        ,  1.73205081],
       [ 1.        ,  2.        ],
       [ 0.        ,  2.23606798],
       [ 1.        ,  2.44948974],
       [ 4.        ,  2.64575131],
       [ 9.        ,  2.82842712],
       [16.        ,  3.        ],
       [25.        ,  3.16227766]])

In [33]:
win = viz.line(
    Y=Y * Y,
    X=Y,
    opts=dict(markers=False),
)

In [38]:
viz.updateTrace(X=np.array([0]),Y=np.array([2,3,4,5]),win=win,name='3')

u'window_361b4c2d156324'

In [39]:
viz.updateTrace(X=np.array([5,6,7]),Y=np.array([6,7,8]),win=win,name='3')

u'window_361b4c2d156324'

In [40]:
viz.updateTrace(X=np.array([8,9,10]),Y=np.array([9,10,11]),win=win,name='3')

u'window_361b4c2d156324'

In [41]:
file = '/home/ubuntu/aws_share/sol/hw2-solution/code/data/VOCdevkit2007/results/VOC2007/Main/comp4_8b1e5a3c-744e-4ff3-842b-c5281f753ee5_det_trainval_aeroplane.txt'

In [42]:
file

'/home/ubuntu/aws_share/sol/hw2-solution/code/data/VOCdevkit2007/results/VOC2007/Main/comp4_8b1e5a3c-744e-4ff3-842b-c5281f753ee5_det_trainval_aeroplane.txt'

In [43]:
fh = open(file,'w')

IOError: [Errno 2] No such file or directory: '/home/ubuntu/aws_share/sol/hw2-solution/code/data/VOCdevkit2007/results/VOC2007/Main/comp4_8b1e5a3c-744e-4ff3-842b-c5281f753ee5_det_trainval_aeroplane.txt'

In [45]:
import os

In [46]:
if not os.path.exists(os.path.dirname(file)):
    try:
        os.makedirs(os.path.dirname(file))
    except OSError as exc: # Guard against race condition
        if exc.errno != errno.EEXIST:
            raise