In [ ]:
%run main.py

=> creating model 'localizer_alexnet_robust'
load pretrained module: features.0.weight
load pretrained module: features.0.bias
load pretrained module: features.3.weight
load pretrained module: features.3.bias
load pretrained module: features.6.weight
load pretrained module: features.6.bias
load pretrained module: features.8.weight
load pretrained module: features.8.bias
load pretrained module: features.10.weight
load pretrained module: features.10.bias
load pretrained module: classifier.1.weight
load pretrained module: classifier.1.bias
load pretrained module: classifier.3.weight
load pretrained module: classifier.3.bias
load pretrained module: classifier.5.weight
load pretrained module: classifier.5.bias
LocalizerAlexNetRobust(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace)
    (2): MaxPool2d(kernel_size=(3, 3), stride=(2, 2), dilation=(1, 1), ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), str

Test: [100/155]	Time 0.172 (0.173)	Loss 0.4817 (0.4812)	Metric1 0.438 (0.402)	Metric2 0.481 (0.482)
Test: [110/155]	Time 0.104 (0.172)	Loss 0.4780 (0.4811)	Metric1 0.562 (0.405)	Metric2 0.481 (0.482)
Test: [120/155]	Time 0.102 (0.171)	Loss 0.4784 (0.4811)	Metric1 0.531 (0.405)	Metric2 0.481 (0.482)
Test: [130/155]	Time 0.102 (0.171)	Loss 0.4789 (0.4811)	Metric1 0.312 (0.408)	Metric2 0.483 (0.482)
Test: [140/155]	Time 0.343 (0.172)	Loss 0.4792 (0.4811)	Metric1 0.469 (0.408)	Metric2 0.482 (0.482)
Test: [150/155]	Time 0.101 (0.171)	Loss 0.4841 (0.4812)	Metric1 0.469 (0.406)	Metric2 0.480 (0.482)
 * Metric1 0.405 Metric2 0.482
> /home/ubuntu/aws_share/sol/hw2-solution/code/free_loc/main.py(197)main()
-> save_checkpoint({
(Pdb) l
192  	            is_best =  score > best_prec1
193  	            best_prec1 = max(score, best_prec1)
194  	            data_log.scalar_summary(tag='valid/metric1',value=m1,step= epoch)
195  	            data_log.scalar_summary(tag='valid/metric2',value=m2,step= ep

Test: [150/155]	Time 0.107 (0.157)	Loss 0.2453 (0.2377)	Metric1 0.469 (0.406)	Metric2 0.480 (0.482)
 * Metric1 0.405 Metric2 0.482
> /home/ubuntu/aws_share/sol/hw2-solution/code/free_loc/main.py(196)main()
-> import pdb;pdb.set_trace()
(Pdb) l
191  	            # remember best prec@1 and save checkpoint
192  	            is_best =  score > best_prec1
193  	            best_prec1 = max(score, best_prec1)
194  	            data_log.scalar_summary(tag='valid/metric1',value=m1,step= epoch)
195  	            data_log.scalar_summary(tag='valid/metric2',value=m2,step= epoch)
196  ->	            import pdb;pdb.set_trace()
197  	            save_checkpoint({
198  	                'epoch': epoch + 1,
199  	                'arch': args.arch,
200  	                'state_dict': model.state_dict(),
201  	                'best_prec1': best_prec1,
(Pdb) m1
0.4052907915993538
(Pdb) m2
0.48151206330782886


In [ ]:
sort_idx = sorted(range(len(s)), key=lambda k: s[k])
s = 
1.00000e-02 *
 -3.3849
  7.7134
 -0.0527
  3.1875
 -3.8390
  5.3175
 -1.7844
 -0.5416
  4.0468
  5.4217
 -3.2040
 -4.2584
 -3.1523
 -2.8485
 -0.9132
  5.6033
  2.3821
 -2.0710
  6.1880
 -2.1397

sort_idx  = [11, 4, 0, 10, 12, 13, 19, 17, 6, 14, 7, 2, 16, 3, 8, 5, 9, 15, 18, 1]


In [1]:
a = [1,2,3,4,5]

In [3]:
import numpy as np
np.where(a>3)

(array([0]),)

In [4]:
x = np.arange(9.).reshape(3, 3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [5]:
np.hstack(np.where( x > 5 ))

(array([2, 2, 2]), array([0, 1, 2]))

In [7]:
np.vstack(np.where( x > 5 ))

array([[2, 2, 2],
       [0, 1, 2]])

In [8]:
np.hstack(np.where( x > 5 ))

array([2, 2, 2, 0, 1, 2])

In [16]:
a = np.array([2, 23, 15, 7, 9, 11, 17, 19, 5, 3])

In [18]:
np.where(a>10,1,0)

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0])

In [19]:
a

array([ 2, 23, 15,  7,  9, 11, 17, 19,  5,  3])

In [13]:
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])