In [3]:
%run main.py

=> creating model 'localizer_alexnet'
LocalizerAlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace)
    (2): MaxPool2d(kernel_size=(3, 3), stride=(2, 2), dilation=(1, 1), ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace)
    (5): MaxPool2d(kernel_size=(3, 3), stride=(2, 2), dilation=(1, 1), ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace)
  )
  (classifier): Sequential(
    (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1))
    (1): ReLU(inplace)
    (2): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
    (3): ReLU(inplace)
    (4): Conv2d(256, 20, kernel_size=(1, 1

AssertionError: Path does not exist: /home/ubuntu/aws_share/hw2-release/code/data/VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt

In [4]:
sb

NameError: name 'sb' is not defined

In [ ]:
sort_idx = sorted(range(len(s)), key=lambda k: s[k])
s = 
1.00000e-02 *
 -3.3849
  7.7134
 -0.0527
  3.1875
 -3.8390
  5.3175
 -1.7844
 -0.5416
  4.0468
  5.4217
 -3.2040
 -4.2584
 -3.1523
 -2.8485
 -0.9132
  5.6033
  2.3821
 -2.0710
  6.1880
 -2.1397

sort_idx  = [11, 4, 0, 10, 12, 13, 19, 17, 6, 14, 7, 2, 16, 3, 8, 5, 9, 15, 18, 1]


In [1]:
a = [1,2,3,4,5]

In [3]:
import numpy as np
np.where(a>3)

(array([0]),)

In [4]:
x = np.arange(9.).reshape(3, 3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [5]:
np.hstack(np.where( x > 5 ))

(array([2, 2, 2]), array([0, 1, 2]))

In [7]:
np.vstack(np.where( x > 5 ))

array([[2, 2, 2],
       [0, 1, 2]])

In [8]:
np.hstack(np.where( x > 5 ))

array([2, 2, 2, 0, 1, 2])

In [16]:
a = np.array([2, 23, 15, 7, 9, 11, 17, 19, 5, 3])

In [18]:
np.where(a>10,1,0)

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0])

In [19]:
a

array([ 2, 23, 15,  7,  9, 11, 17, 19,  5,  3])

In [13]:
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])